package com.musicplayer.melodex.ui.theme

import androidx.compose.ui.graphics.Color

// M3 Expressive 调色板 — 偏蓝紫的充满活力的配色，向更深色调扩展以获得更强的对比度
val Seed = Color(0xFF4A5CF7) // 充满活力的紫蓝色

// ── 浅色主题 ──
val LightPrimary = Color(0xFF3451E0)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFDCE1FF)
val LightOnPrimaryContainer = Color(0xFF001452)
val LightSecondary = Color(0xFF595D72)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFDEE1F9)
val LightOnSecondaryContainer = Color(0xFF161A2C)
val LightTertiary = Color(0xFF735572)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFFFFD6F9)
val LightOnTertiaryContainer = Color(0xFF2A132C)
val LightError = Color(0xFFBA1A1A)
val LightOnError = Color(0xFFFFFFFF)
val LightErrorContainer = Color(0xFFFFDAD6)
val LightOnErrorContainer = Color(0xFF410002)
val LightBackground = Color(0xFFFBF8FF)
val LightOnBackground = Color(0xFF1B1B21)
val LightSurface = Color(0xFFFBF8FF)
val LightOnSurface = Color(0xFF1B1B21)
val LightSurfaceVariant = Color(0xFFE2E1EC)
val LightOnSurfaceVariant = Color(0xFF45464F)
val LightOutline = Color(0xFF757680)
val LightOutlineVariant = Color(0xFFC5C5D0)
val LightInverseSurface = Color(0xFF303036)
val LightInverseOnSurface = Color(0xFFF2F0F7)
val LightInversePrimary = Color(0xFFB8C4FF)

// ── 深色主题 ──
val DarkPrimary = Color(0xFFB8C4FF)
val DarkOnPrimary = Color(0xFF002181)
val DarkPrimaryContainer = Color(0xFF1436C7)
val DarkOnPrimaryContainer = Color(0xFFDCE1FF)
val DarkSecondary = Color(0xFFC2C5DD)
val DarkOnSecondary = Color(0xFF2B3042)
val DarkSecondaryContainer = Color(0xFF414659)
val DarkOnSecondaryContainer = Color(0xFFDEE1F9)
val DarkTertiary = Color(0xFFE2BBDC)
val DarkOnTertiary = Color(0xFF422842)
val DarkTertiaryContainer = Color(0xFF5A3E59)
val DarkOnTertiaryContainer = Color(0xFFFFD6F9)
val DarkError = Color(0xFFFFB4AB)
val DarkOnError = Color(0xFF690005)
val DarkErrorContainer = Color(0xFF93000A)
val DarkOnErrorContainer = Color(0xFFFFDAD6)
val DarkBackground = Color(0xFF131318)
val DarkOnBackground = Color(0xFFE4E1E9)
val DarkSurface = Color(0xFF131318)
val DarkOnSurface = Color(0xFFE4E1E9)
val DarkSurfaceVariant = Color(0xFF45464F)
val DarkOnSurfaceVariant = Color(0xFFC5C5D0)
val DarkOutline = Color(0xFF8F909A)
val DarkOutlineVariant = Color(0xFF45464F)
val DarkInverseSurface = Color(0xFFE4E1E9)
val DarkInverseOnSurface = Color(0xFF303036)
val DarkInversePrimary = Color(0xFF3451E0)